#!/bin/sh

uci -q get system.@personal_init[0] > /dev/null || uci -q add system personal_init > /dev/null

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'

	set system.@personal_init[0].system_chn='1'
	commit system
EOF

# Keep the OpenWrt-generated APK repositories unchanged.
exit 0
