#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -f "/www/luci-static/resources/view/status/include/29_ethinfo.js"
rm -f "/tmp/luci-indexcache"
rm -rf "/tmp/luci-modulecache"

uci set luci.main.mediaurlbase=/luci-static/argon

#设置root密码
sed -i '/^root:/c\root:$6$gyMxdm3KrPiL87$Lgn9dsvhiozWbH/HYoXeQmx4VdGU8fSv91NTvNGGDRHkVBIMOLCrl.2m42CD.2OBP4Ee26ho.3YqXCVXZKdJ1.::0:99999:7:::' /etc/shadow

#加入dropbear ssh_key
touch /etc/dropbear/authorized_keys
chmod 600 /etc/dropbear/authorized_keys
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO728MqlrMNZUA9dqa/bzRL1mMOy5QJhP96l+LxchoH/ misc|wang1zhendire@hotmail.com" >> /etc/dropbear/authorized_keys

#设置默认ip地址
uci set network.lan.proto='dhcp'
#uci delete network.lan.ipaddr
#uci delete network.lan.netmask
#uci delete network.lan.gateway
#uci delete network.lan.dns
uci set network.lan.ip6assign='64'
#my custom settings
uci delete network.@device[0].ports
uci add_list network.@device[0].ports='eth0'
uci add_list network.@device[0].ports='eth1'
uci add_list network.@device[0].ports='eth2'
uci add_list network.@device[0].ports='eth3'
uci delete network.wan
uci delete network.wan6
uci commit network

#设置web管理端口
uci delete uhttpd.main.listen_http
uci delete uhttpd.main.listen_https
uci add_list uhttpd.main.listen_http='0.0.0.0:8888'
uci add_list uhttpd.main.listen_http='[::]:8888'
uci commit uhttpd

exit 0
